# copy custom config to /usr/local/apache2/conf/httpd.conf
# copy public files to /usr/local/apache2/htdocs/
# docker run -dit --name my-apache-app -p 8082:80 httpd to run server locally
FROM httpd:alpine
COPY . /usr/local/apache2/htdocs/