apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
      run: hello-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
        run: hello-world
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: apaches-published
spec:
  ports:
    - name: web
      port: 6969
      targetPort: 8080
      protocol: TCP
  selector:
    run: hello-world
  type: LoadBalancer